name: CDK CI

on:
  create

jobs:

  release:
    name: Build and Release
    runs-on: ubuntu-latest
    # needs: build
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - uses: actions/checkout@v2
      - run: |
          go get github.com/mitchellh/gox
          go get github.com/tcnksm/ghr
          sudo apt-get install -y upx
      - run: bash ./scripts/build_and_release.sh || exit 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
